"""add client portal tokens, notification logs, shop settings

Revision ID: 94e0f9b7a670
Revises: f40952add73f
Create Date: 2026-08-16 06:54:59.449864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e0f9b7a670'
down_revision = 'f40952add73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('portal_revoked', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_orders_portal_token'), ['portal_token'], unique=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('company_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portal_show_prices', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Server defaults above exist only to backfill pre-existing rows; new
    # inserts should keep relying on the Python-side model defaults.
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('portal_revoked', server_default=None)
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('portal_show_prices', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('portal_show_prices')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_address')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_portal_token'))
        batch_op.drop_column('portal_revoked')
        batch_op.drop_column('portal_token')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_order_id'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
